- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120
    COURSE: "DevOps"
    IS_LIVE: true
    TOOLS: 
    - Linux
    - shell
    - Ansible
    CONCEPTS:
      CI: Jenkins
      SCRIPTING: "Shell. Ansible, Terra, Pythin"
  tasks:
  - name: print course info
    ansible.builtin.debug:
    msg: "Course is {{ COURSE }}, Duration: {{ DURATION}}, is live {{ IS LIVE }}, Tools are: {{ TOOLS, Concepts are: {{ CONCEPTS }}"